# Server Port
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
  baseUri: http://127.0.0.1:${server.port}

model:
  # 设备类型 cpu gpu
  device: cpu
  # 最大设置为 CPU 核心数 (Core Number)
  poolSize: 1
  # 模型路径
  modelPath: /Users/calvin/products/4_apps/image_gan/image_backend/models/
  # 人脸检测模型
  faceModelName: retinaface_traced_model.pt
  # 人像分割模型
  faceSegModelName: parsenet_traced_model.pt
  # 人脸修复模型
  faceGanModelName: gfpgan_traced_model.pt
  # 图像超分模型
  srModelName: realsr_traced_model.pt
